### PR TITLE
Fix parallel builds for agbcc, remove configure artifacts from gcc_arm, attempt to fix travis build, add github workflows CI file

### PR DESCRIPTION
**Pull request by Missingmew**
See title.
Parallel builds for agbcc are fixed by adding `genrtl.h` to the rule that builds the generator executable objects (since all of them depend on it), which in turn fixes parallel builds for the entire thing.
Current master has artifacts from `configure` in gcc_arm which dont need to be kept, since `configure` as called from `build.sh` generates those just fine. Additionally this switches from selectively deleting two artifacts to just `make distclean`.
Travis fails because of not finding `zlib-dev`. According to ubuntu package repos, the package should be called `zlib1g-dev` so this should theoretically fix travis (changes taken from #31 to get travis to work).
Additionally, this PR now includes a github workflows CI config file to potentially drop travis in the future due to their changes in usage for free users.
Changes from #37 have been incorporated, the github workflows file has been modified to build both with and without devkitARM.

### CODE REVIEW

**Comment by rawr51919** [comment]
Looks interesting! Mind if this is rebased so you fix your merge conflicts first?

**Comment by Missingmew** [comment]
Conflicts should be gone now, feel free to do as you like.
Better 1.5 years later than never.

**Comment by rawr51919** [comment]
@Missingmew all the relevant points and more from this PR have been separated into individual PRs each. Please close this PR.

**Comment by Missingmew** [comment]
Closing as requested by @coltongit

**Pull request closed without merging**
